import os 
from dotenv import load_dotenv

load_dotenv()

OPEN_AI_KEY = os.getenv("OPENAI_API_KEY")
PAUSE_SUBSCRIPTION_URL = os.getenv("PAUSE_SUBSCRIPTION_URL")
RENEW_SUBSCRIPTION_URL = os.getenv("RENEW_SUBSCRIPTION_URL")
UPGRADE_SUBSCRIPTION_URL = os.getenv("UPGRADE_SUBSCRIPTION_URL")
CANCEL_SUBSCRIPTION_URL = os.getenv("CANCEL_SUBSCRIPTION_URL")
